apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
  - name: web
    image: dockernaveen02/my-webserver:u
    ports:
    - name: web-port
      containerPort: 80
    resources:
      requests:
        memory: "50Mi"
        cpu: "0.5"
      limits:
        memory: "100Mi"
        cpu: "1"
